---
name: Build

on: [push, pull_request]

jobs:
  plugin_test:
    name: asdf plugin test

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - name: parse-tool-versions
        uses: paulo-ferraz-oliveira/parse-tool-versions@v1
        id: tool-versions

      - name: python
        uses: actions/setup-python@v4
        with:
          python-version: ${{steps.tool-versions.outputs.python}}

      - name: wheel
        run: pip3 install wheel

      - name: plugin-test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: awslocal --version
          version: 0.21
