---
name: Build

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  plugin_test:
    name: asdf plugin test

    strategy:
      matrix:
        os:
          # renovate datasource: github-runners, depName: ubuntu
          - ubuntu-24.04
          # renovate datasource: github-runners, depName: macos
          - macos-14

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: parse-tool-versions
        uses: paulo-ferraz-oliveira/parse-tool-versions@534819f70c0c04d788b49dafc29c8117901277bd # v1.0.3
        id: tool-versions

      - name: python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{steps.tool-versions.outputs.python}}

      - name: wheel
        run: pip3 install wheel

      - name: plugin-test
        uses: asdf-vm/actions/plugin-test@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0
        continue-on-error: true
        with:
          command: awslocal --version
          # renovate datasource: pypi, depName: awscli-local
          version: 0.22.0

      # same as above, but works around an asdf-vm/actions/plugin-test issue where the ref is Nok
      - name: plugin-test
        uses: asdf-vm/actions/plugin-test@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0
        if: failure()
        with:
          command: awslocal --version
          # renovate datasource: pypi, depName: awscli-local
          version: 0.22.0
          giturl: ${{ github.event.pull_request.head.repo.full_name }}
          gitref: ${{ github.head_ref }}
