---
name: Build

on: [push]

jobs:
  plugin_test:
    name: asdf plugin test

    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-12

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4.1.6

      - name: parse-tool-versions
        uses: paulo-ferraz-oliveira/parse-tool-versions@v1
        id: tool-versions

      - name: python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{steps.tool-versions.outputs.python}}

      - name: wheel
        run: pip3 install wheel

      - name: plugin-test
        uses: asdf-vm/actions/plugin-test@v3.0.2
        with:
          command: awslocal --version
          version: 0.21
