---
name: Build

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  plugin_test:
    name: asdf plugin test

    strategy:
      matrix:
        os:
          # renovate datasource: github-runners, depName: ubuntu
          - ubuntu-24.04
          # renovate datasource: github-runners, depName: macos
          - macos-15

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: parse-tool-versions
        uses: paulo-ferraz-oliveira/parse-tool-versions@534819f70c0c04d788b49dafc29c8117901277bd # v1.0.3
        id: tool-versions

      - name: python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{steps.tool-versions.outputs.python}}

      - name: wheel
        run: pip3 install wheel

      - name: plugin-test
        uses: asdf-vm/actions/plugin-test@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
        continue-on-error: true
        with:
          command: awslocal --version
          # renovate datasource: pypi, depName: awscli-local
          version: 0.22.2

      # same as above, but works around an asdf-vm/actions/plugin-test issue where the ref is Nok
      - name: plugin-test
        uses: asdf-vm/actions/plugin-test@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
        if: failure()
        with:
          command: awslocal --version
          # renovate datasource: pypi, depName: awscli-local
          version: 0.22.2
          giturl: ${{ github.event.pull_request.head.repo.full_name }}
          gitref: ${{ github.head_ref }}
