---
name: Build

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  plugin_test:
    name: asdf plugin test

    strategy:
      matrix:
        os:
          # renovate datasource: github-runners, depName: ubuntu
          - ubuntu-24.04
          # renovate datasource: github-runners, depName: macos
          - macos-26

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: parse-tool-versions
        uses: paulo-ferraz-oliveira/parse-tool-versions@62d3a3f201712424ce3ed6723eeb97da195dc1a6 # v1.1.0
        id: tool-versions

      - name: python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{steps.tool-versions.outputs.python}}

      - name: wheel
        run: pip3 install wheel

      - name: plugin-test
        uses: asdf-vm/actions/plugin-test@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
        continue-on-error: true
        with:
          command: awslocal --version
          # renovate datasource: pypi, depName: awscli-local
          version: 0.22.2

      # same as above, but works around an asdf-vm/actions/plugin-test issue where the ref is Nok
      - name: plugin-test
        uses: asdf-vm/actions/plugin-test@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
        if: failure()
        with:
          command: awslocal --version
          # renovate datasource: pypi, depName: awscli-local
          version: 0.22.2
          giturl: ${{ github.event.pull_request.head.repo.full_name }}
          gitref: ${{ github.head_ref }}
