---
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install
        uses: asdf-vm/actions/install@v2

      - name: lint.bash
        run: scripts/lint.bash

  actionlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.6.23
        with:
          args: -color

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # uses .markdownlint.yml for configuration
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: |
            .github/**/*.md
            *.md
            LICENSE

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: |
            .github/workflows/**.yml
            .*.yml
          strict: true
          config_file: .yamllint.yml
