---
name: Lint

"on": [push]

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: install
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2

      - name: lint.bash
        run: scripts/lint.bash

  actionlint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.7.1@sha256:435ecdb63b1169e80ca3e136290072548c07fc4d76a044cf5541021712f8f344
        with:
          args: -color

  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      # uses .markdownlint.yml for configuration
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8 # v16.0.0
        with:
          globs: |
            .github/**/*.md
            *.md
            LICENSE

      - name: yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          file_or_dir: |
            .github/workflows/**.yml
            .*.yml
          strict: true
          config_file: .yamllint.yml
